name: Backend unit test

on:
  push:
    branches: [ "17-fix-backend-tests" ]

jobs:
  build:

    runs-on: ubuntu-18.04

    env:
      FLASK_APP: backend/src/app.py

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install flake8 pytest
        python3 -m pip install -r backend/test/requirements.txt
        python3 -m pip install postgres
    - name: Database
      run: |
        sudo docker run --name postgres-db -e POSTGRES_PASSWORD=docker -p 5432:5432 -d postgres
    - name: Run tests
      run: |
        python3 backend/test/test_auth.py
